names = {
    'Timestamp': 'timestamp',
    'Email Address': 'email',
    'If you are an individual or group participant?': 'type',
    'First Name': 'first_name',
    'Last Name': 'last_name',
    'Date of Birth': 'date_of_birth',
    'Gender': 'gender',
    'Address': 'address',
    'City': 'city',
    'Postal code': 'postal_code',
    'Province': 'province',
    'Phone Number': 'phone',
    'School': 'school',
    'Who is your teacher?': 'teacher',
    'Do you have solo class(es) to register?': 'solo_class_0',
    'Class Number': 'class_number_0',
    'Class number suffix': 'class_suffix_0',
    'Repertoire Title': 'repertoire_title_0',
    ' Repertoire Duration in minutes': 'repertoire_duration_0',
    'Composer': 'composer_0',
    'Accompanist name if have': 'accompanist_name_0',
    'Accompanist Phone Number': 'accompanist_phone_0',
    'Accompanist Email': 'accompanist_email_0',
    'If you have another Class?': 'solo_class_1',
    'Class Number.1': 'class_number_1',
    'Class number suffix.1': 'class_suffix_1',
    'Repertoire Title.1': 'repertoire_title_1',
    ' Repertoire Duration in minutes.1': 'repertoire_duration_1',
    'Composer.1': 'composer_1',
    'Accompanist name if have.1': 'accompanist_name_1',
    'Accompanist Phone Number.1': 'accompanist_phone_1',
    'Accompanist Email.1': 'accompanist_email_1',
    'If you have another Class?.1': 'solo_class_2',
    'Class Number.2': 'class_number_2',
    'Class number suffix.2': 'class_suffix_2',
    'Repertoire Title.2': 'repertoire_title_2',
    ' Repertoire Duration in minutes.2': 'repertoire_duration_2',
    'Composer.2': 'composer_2',
    'Accompanist name if have.2': 'accompanist_name_2',
    'Accompanist Phone Number.2': 'accompanist_phone_2',
    'Accompanist Email.2': 'accompanist_email_2',
    'If you have another Class?.2': 'solo_class_3',
    'Class Number.3': 'class_number_3',
    'Class number suffix.3': 'class_suffix_3',
    'Repertoire Title.3': 'repertoire_title_3',
    ' Repertoire Duration in minutes.3': 'repertoire_duration_3',
    'Composer.3': 'composer_3',
    'Accompanist name if have.3': 'accompanist_name_3',
    'Accompanist Phone Number.3': 'accompanist_phone_3',
    'Accompanist Email.3': 'accompanist_email_3',
    'If you have another Class?.3': 'solo_class_4',
    'Class Number.4': 'class_number_4',
    'Class number suffix.4': 'class_suffix_4',
    'Repertoire Title.4': 'repertoire_title_4',
    ' Repertoire Duration in minutes.4': 'repertoire_duration_4',
    'Composer.4': 'composer_4',
    'Accompanist name if have.4': 'accompanist_name_4',
    'Accompanist Phone Number.4': 'accompanist_phone_4',
    'Accompanist Email.4': 'accompanist_email_4',
    'If you have another Class?.4': 'solo_class_5',
    'Class Number.5': 'class_number_5',
    'Class number suffix.5': 'class_suffix_5',
    'Repertoire Title.5': 'repertoire_title_5',
    ' Repertoire Duration in minutes.5': 'repertoire_duration_5',
    'Composer.5': 'composer_5',
    'Accompanist name if have.5': 'accompanist_name_5',
    'Accompanist Phone Number.5': 'accompanist_phone_5',
    'Accompanist Email.5': 'accompanist_email_5',
    'If you have another Class?.5': 'solo_class_6',
    'Class Number.6': 'class_number_6',
    'Class number suffix.6': 'class_suffix_6',
    'Repertoire Title.6': 'repertoire_title_6',
    ' Repertoire Duration in minutes.6': 'repertoire_duration_6',
    'Composer.6': 'composer_6',
    'Accompanist name if have.6': 'accompanist_name_6',
    'Accompanist Phone Number.6': 'accompanist_phone_6',
    'Accompanist Email.6': 'accompanist_email_6',
    'If you have another Class?.6': 'solo_class_7',
    'Class Number.7': 'class_number_7',
    'Class number suffix.7': 'class_suffix_7',
    'Repertoire Title.7': 'repertoire_title_7',
    ' Repertoire Duration in minutes.7': 'repertoire_duration_7',
    'Composer.7': 'composer_7',
    'Accompanist name if have.7': 'accompanist_name_7',
    'Accompanist Phone Number.7': 'accompanist_phone_7',
    'Accompanist Email.7': 'accompanist_email_7',
    'If you have another Class?.7': 'solo_class_8',
    'Class Number.8': 'class_number_8',
    'Class number suffix.8': 'class_suffix_8',
    'Repertoire Title.8': 'repertoire_title_8',
    ' Repertoire Duration in minutes.8': 'repertoire_duration_8',
    'Composer.8': 'composer_8',
    'Accompanist name if have.8': 'accompanist_name_8',
    'Accompanist Phone Number.8': 'accompanist_phone_8',
    'Accompanist Email.8': 'accompanist_email_8',
    'If you have another Class?.8': 'solo_class_9',
    'Class Number.9': 'class_number_9',
    'Class number suffix.9': 'class_suffix_9',
    'Repertoire Title.9': 'repertoire_title_9',
    ' Repertoire Duration in minutes.9': 'repertoire_duration_9',
    'Composer.9': 'composer_9',
    'Accompanist name if have.9': 'accompanist_name_9',
    'Accompanist Phone Number.9': 'accompanist_phone_9',
    'Accompanist Email.9': 'accompanist_email_9',
    'Do you have a recital class to register?': 'recital_class',
    'Class Number.10': 'class_number_10',
    'Class number suffix.10': 'class_suffix_10',
    'Repertoire Title 1': 'repertoire_title_10_1',
    ' Repertoire Duration 1 in minutes': 'repertoire_duration_10_1',
    'Composer 1': 'composer_10_1',
    'Repertoire Title 2': 'repertoire_title_10_2',
    ' Repertoire Duration 2 in minutes': 'repertoire_duration_10_2',
    'Composer 2': 'composer_10_2',
    'Repertoire Title 3': 'repertoire_title_10_3',
    ' Repertoire Duration 3 in minutes': 'repertoire_duration_10_3',
    'Composer 3': 'composer_10_3',
    'Repertoire Title 4': 'repertoire_title_10_4',
    ' Repertoire Duration 4 in minutes': 'repertoire_duration_10_4',
    'Composer 4': 'composer_10_4',
    'Repertoire Title 5': 'repertoire_title_10_5',
    ' Repertoire Duration 5 in minutes': 'repertoire_duration_10_5',
    'Composer 5': 'composer_10_5',
    'Accompanist name if have.10': 'accompanist_name_10',
    'Accompanist Phone Number.10': 'accompanist_phone_10',
    'Accompanist Email.10': 'accompanist_email_10',
    'Do you have a duet, trio, quartet, or quintet class to register?': 'small_group_11',
    'Class Number.11': 'class_number_11',
    'Class number suffix.11': 'class_suffix_11',
    'Name of the second participant': 'second_participant_11',
    'Repertoire Title.10': 'repertoire_title_11',
    ' Repertoire Duration in minutes.10': 'repertoire_duration_11',
    'Composer.10': 'composer_11',
    'Accompanist name if have.11': 'accompanist_name_11',
    'Accompanist Phone Number.11': 'accompanist_phone_11',
    'Accompanist Email.11': 'accompanist_email_11',
    'Class Number.12': 'class_number_12',
    'Class number suffix.12': 'class_suffix_12',
    'Name of the second participant.1': 'second_participant_12',
    'Name of the third participant': 'third_participant_12',
    'Repertoire Title.11': 'repertoire_title_12',
    ' Repertoire Duration in minutes.11': 'repertoire_duration_12',
    'Composer.11': 'composer_12',
    'Accompanist name if have.12': 'accompanist_name_12',
    'Accompanist Phone Number.12': 'accompanist_phone_12',
    'Accompanist Email.12': 'accompanist_email_12',
    'Class Number.13': 'class_number_13',
    'Class number suffix.13': 'class_suffix_13',
    'Name of the second participant.2': 'second_participant_13',
    'Name of the third participant.1': 'third_participant_13',
    'Name of the fourth participant': 'fourth_participant_13',
    'Repertoire Title.12': 'repertoire_title_13',
    ' Repertoire Duration in minutes.12': 'repertoire_duration_13',
    'Composer.12': 'composer_13',
    'Accompanist name if have.13': 'accompanist_name_13',
    'Accompanist Phone Number.13': 'accompanist_phone_13',
    'Accompanist Email.13': 'accompanist_email_13',
    'Class Number.14': 'class_number_14',
    'Class number suffix.14': 'class_suffix_14',
    'Group name': 'group_name_14',
    'Repertoire Title.13': 'repertoire_title_14',
    ' Repertoire Duration in minutes.13': 'repertoire_duration_14',
    'Composer.13': 'composer_14',
    'Accompanist name if have.14': 'accompanist_name_14',
    'Accompanist Phone Number.14': 'accompanist_phone_14',
    'Accompanist Email.14': 'accompanist_email_14',
    'Group Name': 'group_name_15',
    'Address.1': 'group_address_15',
    'City.1': 'group_city_15',
    'Postal code.1': 'group_postal_code_15',
    'Province.1': 'group_province_15',
    'Phone Number.1': 'group_phone_15',
    'School.1': 'group_school_15',
    'Who is your teacher?.1': 'group_teacher_15',
    'Class Number.15': 'class_number_15',
    'Class number suffix.15': 'class_suffix_15',
    'Repertoire Title 1.1': 'repertoire_title_15_1',
    ' Repertoire Duration 1 in minutes.1': 'repertoire_duration_15_1',
    'Composer 1.1': 'composer_15_1',
    'Repertoire Title 2.1': 'repertoire_title_15_2',
    ' Repertoire Duration 2 in minutes.1': 'repertoire_duration_15_2',
    'Composer 2.1': 'composer_15_2',
    'Repertoire Title 3.1': 'repertoire_title_15_3',
    ' Repertoire Duration 3 in minutes.1': 'repertoire_duration_15_3',
    'Composer 3.1': 'Composer_15_3',
    'Accompanist name if have.15': 'accompanist_name_15',
    'Accompanist Phone Number.15': 'accompanist_phone_15',
    'Accompanist Email.15': 'accompanist_email_15',
    'If you have another class?': 'group_class_16',
    'Class Number.16': 'class_number_16',
    'Class number suffix.16': 'class_suffix_16',
    'Repertoire Title 1.2': 'repertoire_title_16_1',
    ' Repertoire Duration 1 in minutes.2': 'repertoire_duration_16_1',
    'Composer 1.2': 'Composer_16_1',
    'Repertoire Title 2.2': 'repertoire_title_16_2',
    ' Repertoire Duration 2 in minutes.2': 'repertoire_duration_16_2',
    'Composer 2.2': 'Composer_16_2',
    'Repertoire Title 3.2': 'repertoire_title_16_3',
    ' Repertoire Duration 3 in minutes.2': 'repertoire_duration_16_3',
    'Composer 3.2': 'Composer_16_3',
    'Accompanist name if have.16': 'accompanist_name_16',
    'Accompanist Phone Number.16': 'accompanist_phone_16',
    'Accompanist Email.16': 'accompanist_email_16',
    'If you have another class?.1': 'group_class_17',
    'Class Number.17': 'class_number_17',
    'Class number suffix.17': 'class_suffix_17',
    'Repertoire Title 1.3': 'repertoire_title_17_1',
    ' Repertoire Duration 1 in minutes.3': 'repertoire_duration_17_1',
    'Composer 1.3': 'Composer_17_1',
    'Repertoire Title 2.3': 'repertoire_title_17_2',
    ' Repertoire Duration 2 in minutes.3': 'repertoire_duration_17_2',
    'Composer 2.3': 'Composer_17_2',
    'Repertoire Title 3.3': 'repertoire_title_17_3',
    ' Repertoire Duration 3 in minutes.3': 'repertoire_duration_17_3',
    'Composer 3.3': 'Composer_17_3',
    'Accompanist name if have.17': 'accompanist_name_17',
    'Accompanist Phone Number.17': 'accompanist_phone_17',
    'Accompanist Email.17': 'accompanist_email_17',
    'Total registration fee': 'total_fee',
    'Have you paid the registration fee?': 'fee_paid',
    'Comments': 'comments',
    'Do you wish to be eligible for the National Music Festival?': 'national_festival',
}