# FIRST STAGE
FROM python:3.12-slim AS first-stage

RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    python3-setuptools

RUN pip install --no-cache-dir --prefix=/ps-install psycopg2

# FINAL STAGE
FROM python:3.12-slim AS final-stage

RUN apt-get update && apt-get install -y \
    libpq-dev \
    default-jre \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY --from=first-stage /ps-install /usr/local

WORKDIR /mfo-app
COPY mfo/  ./mfo
COPY tests/  ./tests
COPY production.env requirements-prod.txt ./

ENV FLASK_APP="mfo.app"
ENV FLASK_ENV="production"

RUN pip install --no-cache-dir -r requirements-prod.txt

EXPOSE 8000

ENTRYPOINT ["gunicorn", "-w", "4", "-b", "0.0.0.0:8000", "mfo.wsgi:app"]